### ISSUE TITLE
geoknife: data discovery

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#108]
Parent: geoknife: accessing gridded data

What data can be accessed using geoknife?

- GeoDataPortal (GDP)
- Datasets not in GDP
- Advantages of remote processing

**Comment by lindsaycarr** [comment]
In setting process algorithm example, waiting for GDP to update the names of the available data sets. Currently, two are named `OPeNDAP Subset`. Shouldn't have to fix anything in code. Just need to update geoknife and re-knit.

```
default_knife <- webprocess()
default_algorithms['OPeNDAP Subset']
$`OPeNDAP Subset`
[1] "gov.usgs.cida.gdp.wps.algorithm.FeatureTimeSeriesAlgorithm"

# expect it to be gov.usgs.cida.gdp.wps.algorithm.FeatureCoverageOPeNDAPIntersectionAlgorithm
```

**Comment by lindsaycarr** [comment]
@jiwalker-usgs any idea when that will be updated?

**Comment by jiwalker-usgs** [comment]
I fixed it in the code, we just need to release and deploy.  Not sure of timeline.

**Comment by lindsaycarr** [comment]
OK, I'll check back in on this one in a little while.

**Comment by lindsaycarr** [comment]
@jiwalker-usgs when was the last geoknife release? Just updated to v1.5.5 but I still get the output from before.

**Comment by jiwalker-usgs** [comment]
This is actually the GDP release that will fix this, I'm working on pushing it out today.
